<a href="https://colab.research.google.com/github/bhanu-4290/ML-AI/blob/main/NLP_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings("ignore")

In [ ]:
data =pd.read_csv('/content/Language_Detection_Dataset.csv')
data

Text  language
0      klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1      sebes joseph pereira thomas  på eng the jesuit...   Swedish
2      ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3      விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4      de spons behoort tot het geslacht haliclona en...     Dutch
...                                                  ...       ...
21995  hors du terrain les années  et  sont des année...    French
21996  ใน พศ  หลักจากที่เสด็จประพาสแหลมมลายู ชวา อินเ...      Thai
21997  con motivo de la celebración del septuagésimoq...   Spanish
21998  年月，當時還只有歲的她在美國出道，以mai-k名義推出首張英文《baby i like》，由...   Chinese
21999   aprilie sonda spațială messenger a nasa și-a ...  Romanian

[22000 rows x 2 columns]

In [ ]:
data.head(10)

Text  language
0  klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1  sebes joseph pereira thomas  på eng the jesuit...   Swedish
2  ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3  விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4  de spons behoort tot het geslacht haliclona en...     Dutch
5  エノが行きがかりでバスに乗ってしまい、気分が悪くなった際に助けるが、今すぐバスを降りたいと運...  Japanese
6  tsutinalar i̇ngilizce tsuutina kanadada albert...   Turkish
7  müller mox figura centralis circulorum doctoru...     Latin
8  برقی بار electric charge تمام زیرجوہری ذرات کی...      Urdu
9  シャーリー・フィールドは、サン・ベルナルド・アベニュー沿い市民センターとrtマーティン高校に...  Japanese

In [ ]:
len(data.language.value_counts())

22

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(data.Text,data.language,test_size=0.2,random_state=42)

In [ ]:
label = LabelEncoder()
y_train_el = label.fit_transform(y_train)
y_test_el = label.transform(y_test)

In [ ]:
len(set(y_test_el))

22

In [ ]:
from string import punctuation
def preprocess(text):
    data = word_tokenize(text)
    data = [i for i in data if i not in punctuation ]
    data = " ".join(data)
    return data


In [ ]:
import nltk
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
x_train_final= x_train.apply(preprocess)
x_test_final= x_test.apply(preprocess)

In [ ]:
x_train_final

5207     สัมประสิทธิ์ฮอลล์ ฟิสิกส์ไฟฟ้า เกี่ยวกับสนามแม...
4450     เกิดวันที่ พฤศจิกายน ภาคอะนิเมะ คดีฆาตกรรมบนจอ...
7033     i omgivningarna runt manigotagan river park re...
487      நிஞ்சா ஹட்டோரி 忍者ハットリくん ninja hattori என்பது க...
19537    эта страница деятельности м в ломоносова — ярк...
                               ...                        
11964    باباجان غفورف تاریخ‌دان و نویسندهٔ کتاب تاریخ ...
21575    en fue invitado por fernando ii para ocupar la...
5390     doğu kanada atabasklarına geleneksel olarak dü...
860      پژواک د يوې ځانگړې پروژې په توگه د اساسي قانون...
15795    テンサイについては糖分を高度に精製する必要があることからサトウキビと同じような黒糖を作るのは...
Name: Text, Length: 17600, dtype: object

In [ ]:
 #TFIDF


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
tf = TfidfVectorizer(lowercase=True,stop_words='english',max_df=0.95,max_features=1000)
tf_train = tf.fit_transform(x_train_final).toarray()
tf_test = tf.transform(x_test_final).toarray()

In [ ]:
tf_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tf_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.07816343, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(tf_train,y_train_el)

MultinomialNB()

In [ ]:
y_pred = model.predict(tf_test)
y_pred

array([17, 15, 10, ...,  3, 13,  2])

In [ ]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test_el, y_pred)
acc

0.8825

In [ ]:
def predict_lang(text):
    x = preprocess(text)
    data = tf.transform([x]).toarray()
    lang = model.predict(data)
    lang = label.inverse_transform(lang)
    return lang[0]

In [ ]:
predict_lang('Me llamo Mondly')

'Swedish'

In [ ]:
predict_lang('விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர..')

'Tamil'

In [ ]:
!pip install gradio

In [ ]:
import gradio as gr
import pandas as pd
from nltk.tokenize import word_tokenize
from string import punctuation
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import nltk
import warnings
warnings.simplefilter('ignore')

# Download required NLTK resources
nltk.download('punkt')

# Load dataset
data = pd.read_csv("Language_Detection_Dataset.csv")

# Splitting dataset into training and testing
x_train, x_test, y_train, y_test = train_test_split(data.Text, data.language, test_size=0.2, random_state=42)

# Encode language labels into numerical values
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Text preprocessing function
def preprocess(text):
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in punctuation]
    return " ".join(tokens)

# Apply preprocessing to training and testing text data
x_train_processed = x_train.apply(preprocess)
x_test_processed = x_test.apply(preprocess)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(lowercase=True, stop_words='english', max_df=0.95, max_features=1000)
x_train_tfidf = vectorizer.fit_transform(x_train_processed).toarray()
x_test_tfidf = vectorizer.transform(x_test_processed).toarray()

# Train Naive Bayes Model
model = MultinomialNB()
model.fit(x_train_tfidf, y_train_encoded)

# Prediction function for Gradio
def predict_language(text):
    processed_text = preprocess(text)  # Preprocess input text
    transformed_text = vectorizer.transform([processed_text]).toarray()  # Convert to TF-IDF
    prediction = model.predict(transformed_text)  # Predict language
    language = label_encoder.inverse_transform(prediction)[0]  # Convert label to language name
    return f"Predicted Language: {language}"  # Return prediction

# Gradio Interface
iface = gr.Interface(
    fn=predict_language,
    inputs=gr.Textbox(placeholder="Enter a sentence..."),
    outputs=gr.Textbox(),
    title="Language Identifier",
    description="Enter a sentence, and the model will predict its language."
)

# Launch Gradio app
iface.launch(share=True)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://315a1786970ceb6106.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
